---
title: "Datafest 2019"
author: "Game of Theories"
date: "4/5/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Importing data
games <- read.csv("~/data-for-datafest-2019/games.csv")
gps <- read.csv("~/data-for-datafest-2019/gps.csv")
rpe <- read.csv("~/data-for-datafest-2019/rpe.csv")
wellness <- read.csv("~/data-for-datafest-2019/wellness.csv")
```

```{r}
# Installing libraries
library(dplyr)
library(ggplot2)
library(e1071)
library(neuralnet)
library(purrr)
library(magrittr)
library(tidyverse)
library(readr)
library(dplyr)
library(tidyr)
library(plotly)
library(reshape2)
library(chron)
library(leaps)
```

```{r}
head(games)
head(gps)
head(rpe)
head(wellness)
```


#Data Cleaning
--------------------------------------------------------------
```{r}
#Shyam
```


```{r}
# Proprietary datasets
gamesJack <- games
gpsJack <- gps
rpeJack <- rpe
wellnessJack <- wellness
wellnessJack <- wellnessJack[, -c(7,8)]

ggplot(wellnessJack, aes(SleepHours, Fatigue)) +
  geom_point()


```


# Cameron's section
```{r}
gamesCameron <- games
gpsCameron <- gps
rpeCameron <- rpe
wellnessCameron <- wellness
```

```{r}
wellnessCameron_scales <- wellnessCameron %>% select(Fatigue, Soreness, Desire, Irritability, SleepQuality)
cormat <- round(cor(wellnessCameron_scales), 2)
melted_cormat <- melt(cormat)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()
```

--------------------------------------------------------------


```{r}
# Creating samples
```

--------------------------------------------------------------
```{r}
#Jon 
gamesJon <- games
gpsJon <- gps
rpeJon <- rpe
wellnessJon <- wellness


AllJon=regsubsets(Fatigue~ Soreness+Desire+Irritability+SleepHours+SleepQuality+Pain+Illness+Menstruation+Nutrition+NutritionAdjustment+USG+TrainingReadiness, data=wellnessJon, nbest=2)
          
```
```{r}
library(car)
AllWJon=lm(Fatigue~ Soreness+Desire+Irritability+SleepHours+SleepQuality+Pain+Illness+Menstruation+Nutrition+NutritionAdjustment+USG+TrainingReadiness, data=wellnessJon)
str(wellnessJon)
```


```{r}
pairs(~Fatigue+Soreness+Desire+Irritability+SleepHours+SleepQuality+Pain+Illness+Menstruation+Nutrition+NutritionAdjustment+USG+TrainingReadiness, data=wellnessJon)


```

```{r}
wellnessJon$Pain= ifelse(wellnessJon$Pain=='Yes',1,0)
wellnessJon$Illness= ifelse(wellnessJon$Illness=='Yes',2,ifelse(wellnessJon$Illness=='Slightly Off', 1,0))
wellnessJon$Menstruation=ifelse(wellnessJon$Menstruation=='Yes',1,0)
wellnessJon$Nutrition=ifelse(wellnessJon$Nutrition=='Excellent',2,ifelse(wellnessJon$Nutrition=='Okay',1,0))
wellnessJon$NutritionAdjustment=ifelse(wellnessJon$NutritionAdjustment=='Yes', 1,0)

wellnessJon<- wellnessJon[-c(11,17)]
graph.correlations(wellnessJon, 0.5)
```


--------------------------------------------------------------
#Ryan's Section

#Creating Dataset marked by intervals
```{r}
#Separating Minutes
MinutesClock <- strsplit(as.character(gps$GameClock), ":")
MinutesClock <- sapply(MinutesClock, "[[", 2)
gps$MinutesClock <- MinutesClock

#Condensing Dataset by Minutes
Minutes.gps = gps %>%
  group_by(PlayerID, GameID, Half, MinutesClock) %>%
  summarize_if(is.numeric, mean)

Minutes.gps$MinutesClock <- as.numeric(Minutes.gps$MinutesClock)
```


```{r}
head(Minutes.gps)
```

```{r}

```



#Creating Dataset marked by intervals
```{r}
#Separating Minutes
MinutesClock <- strsplit(as.character(gps$GameClock), ":")
MinutesClock <- sapply(MinutesClock, "[[", 2)
gps$MinutesClock <- MinutesClock

#Condensing Dataset by Minutes
Minutes.gps = gps %>%
  group_by(PlayerID, GameID, Half, MinutesClock) %>%
  summarize_if(is.numeric, mean)
```

```{r}
head(Minutes.gps)
```

#Combining Everything into one full dataset
```{r}
#Full dataset = combo of all
FullDataset <- games
FullDataset$GameID <- games$'ï..GameID'
FullDataset$'ï..GameID' <- NULL
FullDataset <- full_join(FullDataset, Minutes.gps)
FullDataset <- full_join(FullDataset, rpe)
FullDataset <- full_join(FullDataset, wellness)
```
```{r}
#View
head(FullDataset)
```

```{r}
#Ryan
#Summarized GPS by player
summarized.players = 
  gps %>%
  group_by(PlayerID) %>%
  summarize_if(is.numeric, mean)
str(summarized.players)
```

```{r}
#Function that Returns Graphs of the variables with the greatest correlations
graph.correlations <- function(data, c) {
  data <- data[,map_lgl(data, is.numeric)]
  #Correlation of all Variables
  correlation.matrix <- cor(data, use = "complete.obs")
  correlation.dataset <- as.data.frame(correlation.matrix)
  most.correlation <- which(abs(correlation.matrix) < 1 & abs(correlation.matrix) > c)

  rows.list <- list()
  columns.list <- list()
  j <- 1
  #For Loop for finding maximum correlations
  for(i in most.correlation) {
    #Correlation
    row <- ceiling(i/ncol(data))
    column <- ifelse(i%%ncol(data) == 0, ncol(data), i%%ncol(data))
    rows.list[[j]] <- rownames(correlation.dataset[row,])
    columns.list[[j]] <- names(correlation.dataset)[column]
    j = j+1
  }

  row.column.names = cbind(rows.list, columns.list)

  #New Dataframe To hold Rows/ Columns
  row.column.dataframe <- data.frame(
    row = NULL,
    column = NULL
  )
  #putting values in dataframe
  for(i in 1:length(rows.list)) {
    newRow = data.frame(row = rows.list[[i]], column = columns.list[[i]])
    row.column.dataframe <- rbind(row.column.dataframe, newRow)
  }

  #Changing variable types to character
  row.column.dataframe$row <- as.character(row.column.dataframe$row)
  row.column.dataframe$column <- as.character(row.column.dataframe$column)

  #Removing Duplicates
  for (i in 1:nrow(row.column.dataframe))
  {
      row.column.dataframe[i, ] = sort(row.column.dataframe[i, ])
  }
  row.column.dataframe <- row.column.dataframe[!duplicated(row.column.dataframe),]

  #Dataframe of Variables with the most Correlation
  table <- row.column.dataframe
  
  #creates new dataframe without correlations above c
  new.data = data
  for(i in 1:nrow(table)) {
    new.data[,table[i,2]] <- NULL
  }
  
  #For Loop For Creating Scatterplots of data with the Greatest Correlation
  for(i in 1:nrow(row.column.dataframe)) {
    #Extract column and row variable
    row <- row.column.dataframe[[i, 1]]
    column <- row.column.dataframe[[i, 2]]
    #Plot
    print(ggplot(data) +
      geom_point(aes_string(x = row, y = column), color = "blue4") +
      geom_smooth(aes_string(x = row, y = column)) +
      theme_minimal() +
      ggtitle("Correlations"))
  }
}
```

```{r}
#Graphs Wellness correlations above 0.7
graph.correlations(wellness, 0.7)
```

```{r}
#Graphs RPE correlations above 0.7
graph.correlations(rpe, 0.7)
```

```{r}
#Graph of Minutes.gps with correlations above 0.7
graph.correlations(Minutes.gps, 0.7)
```
```{r}
graph.correlations(FullDataset, 0.7)
```

```{r}
Full.numeric.data = FullDataset[,map_lgl(FullDataset, is.numeric)]
linMod <- lm(Fatigue~., data= Full.numeric.data)

#Backwards Elimination
MSE= (summary(linMod)$sigma)^2
step(linMod, scale=MSE)
```
```{r}
reducedLinMod <- lm(formula = Fatigue ~ TournamentGame + TeamPointsAllowed + GameID + 
    PlayerID + Half + MinutesClock + FrameID + Speed + AccelImpulse + 
    AccelLoad + AccelY + AccelZ + Longitude + Latitude + Duration + 
    RPE + SessionLoad + DailyLoad + AcuteLoad + ChronicLoad + 
    AcuteChronicRatio + ObjectiveRating + Soreness + Desire + 
    Irritability + SleepQuality + MonitoringScore + USG, data = Full.numeric.data)
```

```{r}
Variables <- c("TournamentGame", "TeamPointsAllowed", "GameID", "PlayerID", "Half", "MinutesClock", "FrameID", "Speed", "AccelImpulse", "AccelLoad", "AccelY", "AccelZ", "Longitude", "Latitude", "Duration", "RPE", "SessionLoad", "DailyLoad", "AcuteLoad", "ChronicLoad", "AcuteChronicRatio", "ObjectiveRating", "Soreness", "Desire", "Irritability", "SleepQuality", "MonitoringScore", "USG")

for(v in Variables) {
  plot(FullDataset$Fatigue, FullDataset[,v], ylab = v, xlab = "Fatigue")
}
```
```{r}
for(v in Variables) {
  plot(log(FullDataset$Fatigue), FullDataset[,v], ylab = v, xlab = "log of Fatigue")
}
```

#Graphing Top Correlations with Fatigue
```{r}
#Function that Returns Graphs of the variables with the greatest correlations
graph.correlations.specific <- function(data, c, variable) {
  data <- data[,map_lgl(data, is.numeric)]
  #Correlation of all Variables
  correlation.matrix <- cor(data[,variable], data)
  correlation.dataset <- as.data.frame(correlation.matrix)
  most.correlation <- which(abs(correlation.matrix) < 1 & abs(correlation.matrix) > c)

  rows.list <- list()
  columns.list <- list()
  j <- 1
  #For Loop for finding maximum correlations
  for(i in most.correlation) {
    #Correlation
    row <- ceiling(i/ncol(data))
    column <- ifelse(i%%ncol(data) == 0, ncol(data), i%%ncol(data))
    rows.list[[j]] <- rownames(correlation.dataset[row,])
    columns.list[[j]] <- names(correlation.dataset)[column]
    j = j+1
  }

  row.column.names = cbind(rows.list, columns.list)

  #New Dataframe To hold Rows/ Columns
  row.column.dataframe <- data.frame(
    row = NULL,
    column = NULL
  )
  #putting values in dataframe
  for(i in 1:length(rows.list)) {
    newRow = data.frame(row = rows.list[[i]], column = columns.list[[i]])
    row.column.dataframe <- rbind(row.column.dataframe, newRow)
  }

  #Changing variable types to character
  row.column.dataframe$row <- as.character(row.column.dataframe$row)
  row.column.dataframe$column <- as.character(row.column.dataframe$column)

  #Removing Duplicates
  for (i in 1:nrow(row.column.dataframe))
  {
      row.column.dataframe[i, ] = sort(row.column.dataframe[i, ])
  }
  row.column.dataframe <- row.column.dataframe[!duplicated(row.column.dataframe),]

  #Dataframe of Variables with the most Correlation
  table <- row.column.dataframe
  
  #creates new dataframe without correlations above c
  new.data = data
  for(i in 1:nrow(table)) {
    new.data[,table[i,2]] <- NULL
  }
  
  #For Loop For Creating Scatterplots of data with the Greatest Correlation
  for(i in 1:nrow(row.column.dataframe)) {
    #Extract column and row variable
    row <- row.column.dataframe[[i, 1]]
    column <- row.column.dataframe[[i, 2]]
    #Plot
    print(ggplot(data) +
      geom_point(aes_string(x = row, y = column), color = "blue4") +
      geom_smooth(aes_string(x = row, y = column)) +
      theme_minimal() +
      ggtitle("Correlations"))
  }
}
```

```{r}
graph.correlations.specific <- function(data, c, string_variable) {
  data <- data[, map_lgl(data, is.numeric)]
  no.na <- na.omit(data)
  correlations <- as.data.frame(cor(no.na[,string_variable], no.na))
  correlations <- gather(correlations, key = "Variables", value = "Correlations")
  max.correlations <- filter(correlations, Correlations > c & Correlations < 1)
  max.correlations

  for(v in max.correlations$Variables) {
    print(ggplot(data) +
      geom_point(aes_string(x = v, y = string_variable)) +
      geom_smooth(aes_string(x = v, y = string_variable), , method = "lm")
    )
  }
}
```


```{r}
graph.correlations.specific(FullDataset, 0.5, "AcuteChronicRatio")
```

```{r}
no.na <- na.omit(Full.numeric.data)
linMod.ratio <- lm(AcuteChronicRatio~., data = select(no.na, -contains("Load")))
#Backwards Elimination
MSE= (summary(linMod.ratio)$sigma)^2
step(linMod.ratio, scale=MSE)
```

```{r}
#removed acute and chronic load
reducedMod.ratio <- lm(formula = AcuteChronicRatio ~ TeamPoints + TeamPointsAllowed + 
    GameID + PlayerID + Speed + AccelImpulse + AccelX + AccelY + 
    AccelZ + Longitude + RPE + ObjectiveRating + FocusRating + 
    Fatigue + Soreness + Desire + Irritability + SleepHours + 
    SleepQuality + USG, data = select(no.na, -contains("Load")))

summary(reducedMod.ratio)
```

```{r}
FullDataset = mutate(FullDataset,
                     Group = ifelse(AcuteChronicRatio > 1.2, "Fatigued",
                                    ifelse(AcuteChronicRatio < 0.8, "Recovering", "Safe Range")),
                     isSafe = ifelse(AcuteChronicRatio > 1.2, "No", "Yes"))

```
```{r}
ggplot(filter(FullDataset, !is.na(Group))) +
  geom_point(aes(x = AccelX, y = AccelY, col = Group), size = 3)
```

```{r}
ggplot(filter(FullDataset, !is.na(Group))) +
  geom_point(aes(x = AccelX, y = AccelY, col = isSafe), size = 1)

ggplot(filter(FullDataset, !is.na(Group))) +
  geom_point(aes(x = AccelX, y = AccelZ, col = isSafe), size = 1)

ggplot(filter(FullDataset, !is.na(Group))) +
  geom_point(aes(x = AccelY, y = AccelZ, col = isSafe), size = 1)
```
```{r}
ggplot(filter(FullDataset, !is.na(Group))) +
  geom_boxplot(aes(x = isSafe, y = Fatigue, fill = isSafe))
```
```{r}
ggplot(filter(FullDataset, !is.na(Group)))
  geom_boxplot(aes(x = isSafe, y = AccelZ, fill = isSafe))
```







#Exploratory Data Analysis
--------------------------------------------------------------
```{r}
#Shyam
```
--------------------------------------------------------------
```{r}
#Cameron
```
--------------------------------------------------------------
```{r}
#Jack Leary
```

```{r}
# Creating samples
```



```{r}
#Jon
```
--------------------------------------------------------------
```{r}
#Jon
```

--------------------------------------------------------------
```{r}
ggplot(na.omit(FullDataset)) +
  geom_histogram(aes(x= Fatigue, fill = Menstruation), binwidth = 0.5) +
  facet_wrap(~Menstruation)
```

```{r}
ggplot(na.omit(FullDataset), aes(x = Menstruation, y = Fatigue)) +
  geom_boxplot(aes(fill = Menstruation))
```
```{r}
ggplot(na.omit(FullDataset), aes(x = Menstruation, y = Soreness)) +
  geom_boxplot(aes(fill = Menstruation))
```
```{r}
ggplot(na.omit(FullDataset), aes(x = Menstruation, y = Desire)) +
  geom_boxplot(aes(fill = Menstruation))
```

#Does this mean that Menstruation helps people play rugby better????
```{r}
#I think yes! - and so does this p value!
summary(aov(Fatigue~Menstruation, data= FullDataset))
```

```{r}
filter(gps, PlayerID == 1)
```

--------------------------------------------------------------


















#Additional Research
--------------------------------------------------------------
```{r}
#Shyam
```
--------------------------------------------------------------
```{r}
#Cameron
```
--------------------------------------------------------------
```{r}
#Jack Leary
```

```{r}
# Creating samples
```
--------------------------------------------------------------
```{r}
#Jon 
```
--------------------------------------------------------------
```{r}
#Ryan
```

